name: Lint, Test & Build on Push action
on: [push]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
        - name: Get code from repo
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm ci
        - name: Run Test cases
          run: npm run test
  deploy:
    needs: [lint, test]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
        - name: Get code from repo
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm ci
        - name: Build application
          run: npm run build
        - name: Deploy to server
          run: echo "Deployment started..."