name: Output Event Details on New Issues created
on: issues

jobs:
  output-event-details:
    runs-on: ubuntu-latest
    steps:
       - name: Output event details
         run: echo Event details "${{ toJSON(github.event) }}"